1048576
tpb 1024 bpg 33
y shape (1024,)
Traceback (most recent call last):
  File "swat_cuda.py", line 451, in <module>
    mod = SourceModule(swatc)
  File "/home/xh/compiler/anaconda2/lib/python2.7/site-packages/pycuda/compiler.py", line 291, in __init__
    arch, code, cache_dir, include_dirs)
  File "/home/xh/compiler/anaconda2/lib/python2.7/site-packages/pycuda/compiler.py", line 254, in compile
    return compile_plain(source, options, keep, nvcc, cache_dir, target)
  File "/home/xh/compiler/anaconda2/lib/python2.7/site-packages/pycuda/compiler.py", line 137, in compile_plain
    stderr=stderr.decode("utf-8", "replace"))
pycuda.driver.CompileError: nvcc compilation of /tmp/tmp4llly9/kernel.cu failed
[command: nvcc --cubin -arch sm_61 -I/home/xh/compiler/anaconda2/lib/python2.7/site-packages/pycuda/cuda kernel.cu]
[stderr:
kernel.cu(9): warning: variable "s1" was declared but never referenced

kernel.cu(10): warning: variable "I" was declared but never referenced

kernel.cu(12): warning: variable "tid" was declared but never referenced

kernel.cu(12): warning: variable "W" was declared but never referenced

kernel.cu(157): error: identifier "__shfl_up_sync" is undefined

kernel.cu(168): warning: loop is not reachable

kernel.cu(94): warning: variable "bth" was declared but never referenced

kernel.cu(325): warning: statement is unreachable

kernel.cu(216): warning: variable "ST" was declared but never referenced

kernel.cu(226): warning: variable "bth" was declared but never referenced

kernel.cu(495): warning: loop is not reachable

kernel.cu(377): warning: variable "z" was declared but never referenced

kernel.cu(381): warning: variable "bth" was declared but never referenced

kernel.cu(638): warning: variable "i1" was declared but never referenced

kernel.cu(569): warning: variable "bth" was declared but never referenced

1 error detected in the compilation of "/tmp/tmpxft_0000580d_00000000-7_kernel.cpp1.ii".
]
